CREATE TABLE "GCG_6994_UOM_MAINT" (
 "UOM" VARCHAR(2),
 "DESCRIPTION" VARCHAR(30),
 "FACTOR" DOUBLE,
 "OPERATOR" CHAR(1),
 "TO_UOM" VARCHAR(2),
 "TRACK" BIT NOT NULL,
 "PART" VARCHAR(20),
 "LOCATION" VARCHAR(2),
 "SELECTED" BIT NOT NULL );